import { jwtVerify } from 'jose';

/**
 * User socket authentication data
 * Attached to each socket connection after successful authentication
 */
export interface SocketUserData {
  userId: string;
  isRoot: boolean;
  organizationIds: string[];
  clubIds: string[];
}

/**
 * Convert string to Uint8Array for jose library
 * Works in both browser and Node.js environments
 */
function stringToUint8Array(str: string): Uint8Array {
  if (typeof TextEncoder !== 'undefined') {
    return new TextEncoder().encode(str);
  }
  // Fallback for Node.js environments without TextEncoder
  return new Uint8Array(Buffer.from(str, 'utf-8'));
}

/**
 * Verify JWT token (JWS) and extract user information
 * 
 * This function verifies a signed JWT (JWS) using the HS256 algorithm.
 * The token is generated by /api/socket/token and includes user permissions.
 * 
 * @param token - JWS token from socket auth payload
 * @returns User data if token is valid, null otherwise
 */
export async function verifySocketToken(token: string): Promise<SocketUserData | null> {
  try {
    // Validate token type - must be a non-empty string
    if (!token || typeof token !== 'string') {
      console.error('[SocketAuth] Invalid token type:', typeof token);
      return null;
    }

    // Ensure token is not just whitespace
    if (token.trim() === '') {
      console.error('[SocketAuth] Token is empty or whitespace');
      return null;
    }

    // Get secret from environment
    const secret = process.env.AUTH_SECRET || process.env.NEXTAUTH_SECRET;
    if (!secret) {
      console.error('[SocketAuth] AUTH_SECRET not configured');
      return null;
    }

    // Verify the JWS token using jose
    const { payload } = await jwtVerify(
      token,
      stringToUint8Array(secret),
      {
        algorithms: ['HS256'], // Only accept HS256 algorithm
      }
    );

    // Extract user data from verified payload
    const userId = payload.sub;
    const isRoot = (payload.isRoot as boolean) ?? false;
    const organizationIds = (payload.organizationIds as string[]) || [];
    const clubIds = (payload.clubIds as string[]) || [];

    if (!userId) {
      console.error('[SocketAuth] Invalid token: no user ID found in payload');
      return null;
    }

    console.log('[SocketAuth] User authenticated:', {
      userId,
      isRoot,
      organizationCount: organizationIds.length,
      clubCount: clubIds.length,
    });

    return {
      userId,
      isRoot,
      organizationIds,
      clubIds,
    };
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);
    console.error('[SocketAuth] Token verification failed:', errorMessage);
    return null;
  }
}
